version: '3.8'

services:
  ingot:
    build: .
    image: ingot
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./output_frames:/app/output_frames
      - ./database:/app/database
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONPATH=/app/src
      - RABBITMQ_QUEUE_AUTO_DELETE=false 
    ports:
      - "5002:5002"
    env_file: .env

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5